version: "1.0"
services:
  db:
    image: postgres:16.2-bookworm
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - "./src/db:/docker-entrypoint-initdb.d"
  app:
    image: python:3.12-bookworm
    command: bash /app/startup.sh
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DJANGO_SECRET=${DJANGO_SECRET}
    ports:
      - "8000:8000"
    volumes:
      - "./src/app:/app"
      - "./data:/data"
